<?php

require_once "autoloader.php";

?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Nueva Tarea</title>
<link rel="stylesheet" type="text/css" href="form/view.css" media="all">
</head>
<body id="main_body">
    
    <img id="top" src="form/top.png" alt="">
    <div id="form_container">
    
        <h1><a>Nueva Tarea</a></h1>
        <form class="appnitro" method="post" action="procesarPoder.php">
            <div class="form_description">
                <h2>Nueva Tarea</h2>
                <p>Introduce los datos de la tarea</p>
            </div>
            <ul>
                <li>
                    <label class="nombrePoder" for="nombrePoder">Nombre Poder </label>
                    <div>
                        <input name="nombrePoder" class="element text medium" type="text" maxlength="255" value=""/>
                    </div>
                </li>
                <li>
                    <label class="daño" for="daño">Daño</label>
                    <div>
                        <input name="daño" class="number" type="number"/>
                    </div>
                </li>
                <li>
                    <label class="coste" for="coste">Coste </label>
                    <span>
                        <input name="coste" class="number" type="number"/>
                    </span>
                </li>
                <li>
                    <label class="descripcion" for="descripcion">Descripción</label>
                    <span>
                        <input name="descripcion" class="number" type="text"/>
                    </span>
                </li>
                <li class="buttons">
                    <input type="hidden" name="id" value="12028" />
                    <input class="button_text" type="submit" name="submit" value="Guardar" />
                </li>
            </ul>
        </form>
        <div id="footer">
            Generated by <a href="http://www.floridauniversitaria.es">Florida</a>
        </div>
    </div>
    <img id="bottom" src="form/bottom.png" alt="">
</body>
</html>
